Replace default tests with rspec
railsbump/app pull request #62
Opened 2021-01-03 22:16 UTC by alexeyschepin

Install rspec and make basic setup.

2021-01-19 20:13 UTC, manuelmeurer requested changes
Thanks for your effort, @alexeyschepin!
Could you address the two comments please?

2021-01-19 20:13 UTC, manuelmeurer commented on .gitignore
> +!/tmp/.keep
Please remove these changes.

2021-01-19 20:13 UTC, manuelmeurer commented on Gemfile
> +end
Please add similar version constraints as the other gems have, and indent the constraint properly.

2021-01-22 08:52 UTC, alexeyschepin commented
Hey @manuelmeurer, have a look at the fix, please.

2021-02-15 13:08 UTC, merged

2021-02-15 13:08 UTC, manuelmeurer commented
Thanks, @alexeyschepin and sorry for the delay... 🙇‍♂️